services:
  flask:
    image: ghcr.io/phape/spotify-tools:latest
    container_name: spotifytools
    restart: always
    env_file:
      - .env
    environment:
      - APP_NAME=spotifytools
      - FLASK_ENV=production
    networks:
      - "net"

networks:
  net:
    external: true