# This is for local development. It supplements / overwrites the docker-compose.yml file.
# 

version: "3.7"

services:
  flask:
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
      - FLASK_DEBUG=True

networks:
  net:
    external: true