version: "3.7"

services:
  flask:
    build: ./flask
    container_name: spotifytools
    restart: always
    environment:
      - APP_NAME=spotifytools
      - FLASK_ENV=production
      - FLASK_SECRET_KEY=${FLASK_SECRET_KEY}
      - SPOTIPY_CLIENT_ID=${SPOTIPY_CLIENT_ID}
      - SPOTIPY_CLIENT_SECRET=${SPOTIPY_CLIENT_SECRET}
      - SPOTIPY_REDIRECT_URI=${SPOTIPY_REDIRECT_URI}
      - GENIUS_CLIENT_ACCESS_TOKEN=${GENIUS_CLIENT_ACCESS_TOKEN}
    networks:
      - "net"

networks:
  net:
    external: true