# This file is automatically loaded by Docker Compose
# To run in production mode, use: docker-compose -f docker-compose.yml up -d

services:
  flask:
    build: 
      context: ./flask
      tags:
        - "spotifytools:local-dev"
    image: spotifytools:local-dev
    env_file:
      - .env
    ports:
      - "5000:5000"
    volumes:
      - ./flask:/app
    environment:
      - FLASK_ENV=development
      - FLASK_DEBUG=1
      - FLASK_HOST=0.0.0.0
      - FLASK_PORT=5000
    command: ["python", "app.py"]  # Use Flask dev server with hot reload

networks:
  net: