# This file is automatically loaded by Docker Compose
# To run in production mode, use: docker-compose -f docker-compose.yml up -d

services:
  flask:
    build: ./flask
    env_file:
      - .env
    volumes:
      - ./flask:/app
    environment:
      - FLASK_ENV=development
      - FLASK_DEBUG=1
    command: ["python", "app.py"]  # Use Flask dev server with hot reload

networks:
  net:
    external: true